### ISSUE TITLE
A couple of suggestions

### ISSUE THREAD

**Issue by blushydan** [Fearinn/foolsMate#7]
First of all, great website. But here are a couple of first impression problems, I would change/add:

1. Dropdown box/Select menu for pages felt overly annoying and unorthodox to use. I would make two arrows to go forward/back one page at the time, and a textbox for counter, where you can input needed page. 
2. Changes to Player Dashboard. Total minutes played is very confusing for ordinary user, formatting as hours, or days would be much better, as its easier to visualize than minutes. Also avatars are quite uncomfortable for eye. I would make image sligtly larger and in better quality, default backround (day for light theme, night for dark theme), and image popup on click would be a nice finisher
3. Dark theme. As a dark theme user I burned my eyes :)

**Comment by Fearinn** [comment]
Thanks for the suggestions! Here are my comments on them:

1. I agree a select for pages is odd, it was just the most convenient way to make it work without more code and layout changes. However, I think there are some libs with ready solutions and better UX, so I'll take a look at them.

2. Using hours instead of minutes does sound better, especially because it's the unit used in-game. I will implement it shortly.

3. A dark theme is in the plans, hopefully out soon.

**Comment by Fearinn** [comment]
Hello! I've moved my focus to other stuff, so it's taken a while to apply all suggestions, but it's done!

Although I've not worked on an image popup, the avatars resolution should be much better now. 

I've also added a hamburger menu in the mobile version, what is a relevant visual and UX improvement.

Most commits from a77222fd7f2161a7a9b5a6f4826d99505558c1f2 to 743eb7f906b34fe84c533e743a86d079d6ed1acc are related to this issue.

Feel free to leave more feedback and to open other issues!
